### ISSUE TITLE
Document files

### ISSUE THREAD

**Issue by amitbravo** [cinder92/react-native-get-music-files#1]
Hello, instead of music files, I need to find pdf, doc etc files in entire storage , I am using RNFetchBlob's FS e.g. RNFetchBlob.fs.stat but I have need to use loop over and over again , because it brings only one level files list and then if there is any directory , you loop again to go in and so on, so I am just wondering if somehow using this dependancy there is anything I can update to bring out other files list as well ?

**Comment by cinder92** [comment]
Hey @amitbravo this package is using `android.provider.MediaStore.Audio.Media.EXTERNAL_CONTENT_URI` that extract all songs files in device (SDCard and internal memory) you can try to change this, to get work as you want.
