### ISSUE TITLE
[Remove @Override] Those who are facing compilation errors on RN 0.48

### ISSUE THREAD

**Issue by themakerman** [cinder92/react-native-get-music-files#10]
![issue](https://user-images.githubusercontent.com/14818804/30449865-e37ebf8e-99c2-11e7-8d01-45da8dce2332.jpg)

**Comment by cinder92** [comment]
Thanks @themakerman this is only needed in case your version of RN is 0.29^

**Comment by yusuf987** [comment]
> Thanks @themakerman this is only needed in case your version of RN is 0.29^

in which file ??
