### ISSUE TITLE
JS Thread and UI Thread FPS drops to negative after the native module is called

### ISSUE THREAD

**Issue by themakerman** [cinder92/react-native-get-music-files#11]
I have thoroughly checked and debugged my code. The same code works perfectly on iOS with another native module to retrieve music files. But on android as soon as i call this native module my app starts to lag and the FPS drops to 2-10 and some times even negative. 

I don't know why is this happening? Are there many jumps across the RN bridge? cause i am sure module is rendering my app to slow down making it unusable.

**Comment by cinder92** [comment]
Hello, what is the native module for iOS that you are using? maybe, we can work with android based on that plugin

**Comment by cinder92** [comment]
Fixed in V2

**Comment by themakerman** [comment]
@cinder92 i am using react-native-itunes.
https://github.com/kadiks/react-native-itunes

Actually i am not familiar into native iOS objective C. If you have native experience and can port library to work with iOS then it will be great. Actually if that happens then my production app will be 100% code shared between both platforms.

**Comment by cinder92** [comment]
That library only gets songs from iTunes , not from memory like our repository, and have many differences but we can use a part of that code in order to get same results
