### ISSUE TITLE
invalid column genre 

### ISSUE THREAD

**Issue by 13627491210** [cinder92/react-native-get-music-files#115]
this is my code,  i have a error, invalid column genre 。
my phone's  android version is  10。

and another phone is  android 13 , it's  no problem，works well。

const tracks = await getAll({
          limit: 3000,
          offset: 0,
          coverQuality: 50,
          minSongDuration: 60000,
          sortBy: SortSongFields.TITLE,
          fields: [
            'title',
            'artwork',
            'duration',
            'artist',
            // 'genre',
            // 'lyrics',
            // 'albumTitle',
          ],
          sortOrder: SortSongOrder.ASC,
        });

**Comment by dante-cervantes-rocketlab** [comment]
hey @13627491210 could you please share screen shot of the error? so we can check what is happening there ... also have you upgraded to the latest version of this package? it seems that you are adding `fields` param which is no longer needed. Please take a look to the read-me file.

**Comment by cinder92** [comment]
closing due to no response from issuer

**Comment by baqx** [comment]
I am also facing this same problem
