### ISSUE TITLE
Promise: Unhandled promise rejection id 0,

### ISSUE THREAD

**Issue by gaphu** [cinder92/react-native-get-music-files#14]
calling the function in android is sending unhandled promise rejection, along with the array of the songs in v^2.0.1 but then checked and worked with v2.0.0

**Comment by cinder92** [comment]
Hello could you please check with latest commit in github? we just make a little change, and please tell me what is your platform, and react native version

**Comment by themakerman** [comment]
@cinder92 Same error for me.
React Native version:  0.48.1
react-native-get-music-files version: 2.0.1
OS: Android 7.0

**Comment by themakerman** [comment]
@cinder92 isn't the new commit pushed to npm??

**Comment by trananh2001** [comment]
I have same issue.
React Native version: 0.50.4
react-native-get-music-files version: 2.0.1
OS: Android 4.4

**Comment by themakerman** [comment]
Time being use 2.0.0 version.

**Comment by themakerman** [comment]
@flarocca i think latest commit is not available on npm? Can you take a look at this as well? Many people are facing this issue.

**Comment by flarocca** [comment]
@themakerman That's right, but I can't publish to npm, just the owner.

**Comment by cinder92** [comment]
@themakerman @flarocca i have updated the index.js file in master, please download and try again, it was a reversed callback names

**Comment by flarocca** [comment]
Hi @cinder92, did you update the package on Npm as well? Thanks!!!

**Comment by themakerman** [comment]
Yup npm more important.
