### ISSUE TITLE
[iOS] No callback response, Possible Unhandled Promise Rejection (id: 0)

### ISSUE THREAD

**Issue by CYB3RL1F3** [cinder92/react-native-get-music-files#18]
Hello,

I set up the library on the app I'm currently working on, but get this warning message : Possible Unhandled Promise Rejection (id: 0). I don't get any callback nor error... 

Any clue? 

I set in my info.plist the following key : 

```
<key>NSAppleMusicUsageDescription</key>
	<string>Select and play using with your remote</string>
```

I well receive the permission ask, then nothing. Do I miss something to do ?

**Comment by themakerman** [comment]
Use 2.0.0 for a while. @cinder92 is away i think. Use downgraded version till someone fixes it @CYB3RL1F3

**Comment by thinhvo-groove** [comment]
@CYB3RL1F3 I took a look on codes and found that its Promise callback resolve and reject was swapped. You can go inside the lib to swap it back.

**Comment by cinder92** [comment]
Sorry guys, i have a lot of work, but i hope this weekend i can work with you, the error is in `index.js` line 9, is reversed, it must be `new Promise(resolve, reject)`, i will move it right now

**Comment by cinder92** [comment]
please, try it again, i just merged with master

**Comment by themakerman** [comment]
@cinder92 Gracias.

**Comment by thinhvo-groove** [comment]
@cinder92  thanks man!
