### ISSUE TITLE
Ony mp3 files supported

### ISSUE THREAD

**Issue by thinhvo-groove** [cinder92/react-native-get-music-files#19]
I have tested this library, I found that this lib is only able to scan for mp3 files on Android MediaStore. Can you do something in the future to support all other kinds of sound files?

**Comment by themakerman** [comment]
@flarocca Can we do something on this? @cinder92

**Comment by flarocca** [comment]
I haven't had tume to take a look, but I'll do this week. What's your suggestion? What types of fikes would you like to include?

**Comment by themakerman** [comment]
I think mp4,wav and .aac, most important for (apple) .alac would suffice. We can keep the end goal of supporting all these but for the initial commit we can go with .mp4 and .aac.

**Comment by thinhvo-groove** [comment]
Hi @flarocca!  yeah, as @themakerman mentioned !

**Comment by cinder92** [comment]
hello guys, i need time to work on this again, let me check it :)

**Comment by themakerman** [comment]
@cinder92 Hola Amigo. Welcome back after long time. By the way my music player is ready to be launched. I can release a beta and then if u guys support mp4 and others soon I can release an update.

**Comment by cinder92** [comment]
@themakerman of course! thats awesome! Gracias colega!

**Comment by themakerman** [comment]
@flarocca hey budd, anything on mp4 support? @cinder92

**Comment by cinder92** [comment]
Hey y'all just reading about mp4, its a video format not an audio, i used `https://www.zamzar.com/convert/mp3-to-mp4/` to convert mp3 to mp4 and my computer recognized as video file, this plugin just read audio files, or correct me if i'm wrong.

**Comment by cinder92** [comment]
@themakerman  i was able to recognize mp4 files with this plugin, not need to update nothing, with page that i give you, and the code, its returning mp4 files

![captura de pantalla 2018-06-12 a la s 10 15 23](https://user-images.githubusercontent.com/4725556/41299662-8f85aab4-6e29-11e8-9bde-1bc6c38235a1.jpg)

**Comment by cinder92** [comment]
ok i see what is the error, we are using a mp3file library and FFMPEG in order to get Metadata from songs, so if your mp4 has no metadata, is not going to appear in json file, try turning to false

`comments, date and lyrics from options`
