### ISSUE TITLE
READ FROM SD CARD

### ISSUE THREAD

**Issue by EarvinJay** [cinder92/react-native-get-music-files#22]
I have successfully retrieved songs from my phone's internal storage . why can't I retrieve songs from my sd card? I am using Android v6.0.1

**Comment by cinder92** [comment]
Hello, you should know that this package only reads mp3 (for now), and most of android devices, order differently the song files.

I think you need to put the files in root folder to let the plugin read the songs.

**Comment by EarvinJay** [comment]
Thank you very much for the reply. I have already placed an mp3 song to the
root folder of my sdcard, but it is not included in the response.

**Comment by Drazail** [comment]
I tried to reproduce this, however it seems to be working as intended on 2.1

Would you please provide us with more information?

**Comment by cinder92** [comment]
closing due to no response
