### ISSUE TITLE
在ios端为什么我不能得到歌曲的URI？另外一般如何去播放呢？

### ISSUE THREAD

**Issue by Huii-Wang** [cinder92/react-native-get-music-files#23]

**Comment by cinder92** [comment]
Hello, could you please try to write in english? i can't understand japanese, i won't use google translate for understand what are you trying to say.

Thanks

**Comment by yyrdl** [comment]
@cinder92 he speaks in Chinese ---》 "Why I can not get the URI of the music on IOS? And how to play the music"。  

@Wirhui 这个 模块只是用来获取音乐列表的，播放用其他的模块。

Thanks cinder92 , this module is helpful for me :)

**Comment by cinder92** [comment]
@wirhui the Uri for iOS is named as 'assetUrl' on incoming array and 'path' for Android , to play audio you can use any other react native plugin, because is not the intention of this one
