### ISSUE TITLE
Path and SongID

### ISSUE THREAD

**Issue by ithustle** [cinder92/react-native-get-music-files#25]
Hello,

How can I get path and songId of music?

**Aditional Info**

- RN: 0.54.2
- OS: MacOS High Sierra
- Simulator and Physical Device (iPhone 6)

Thanks

**Comment by cinder92** [comment]
Hello for iOS, the array is a bit different, instead of 'path' you must use 'assetUrl', and for 'id' you must use 'persistentId'

**Comment by ithustle** [comment]
Hello, @cinder92 . Thanks.
