### ISSUE TITLE
 Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [[]:react-native-get-music-files:unspecified]

### ISSUE THREAD

**Issue by NightJolt** [cinder92/react-native-get-music-files#28]
Got this error after installing library:

`:app:processDebugManifest FAILED FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:processDebugManifest'. > Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [[]:react-native-get-music-files:unspecified] C:\Users\[]\Desktop\[]\[]\[]\[]\MusicPlayer\android\app\build\intermediates\exploded-aar\MusicPlayer\react-native-get-music-files\unspecified\AndroidManifest.xml Suggestion: use tools:overrideLibrary="com.cinder92.musicfiles" to force usage * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. BUILD FAILED`

**Comment by YajanaRao** [comment]
How did you resolve this issue?

**Comment by ronniebhatt** [comment]
just increase minSdkVersion to 16

**Comment by ronniebhatt** [comment]
just incease minSdkVrsion to 17
