### ISSUE TITLE
Is there some way to scan the files faster and when will this library support iOS?

### ISSUE THREAD

**Issue by themakerman** [cinder92/react-native-get-music-files#3]
First of all this library is awesome and works very well. The only problem is speed. Is there someway to store the data in cache so that the array loads faster?

**Comment by cinder92** [comment]
Hey @themakerman at this time there is no way to store in cache first list of files, and for iOS version we are working on that!

**Comment by themakerman** [comment]
@cinder92 Great.....Hope you do it soon....Really appreciate the affords you guys are making on RN. Can you just tell me an ETA if you have for iOS support?

**Comment by cinder92** [comment]
Fixed in V2, and iOS development started :)

**Comment by cinder92** [comment]
@themakerman  now this plugin supports iOS, is the same as `react-native-itunes` api, hope it helps

**Comment by themakerman** [comment]
@cinder92 Great. Really thankful mate. Would love to share the app once done.
