### ISSUE TITLE
warning: 'react-native' peer dependency missing

### ISSUE THREAD

**Issue by kidow** [cinder92/react-native-get-music-files#30]
<img width="716" alt="2018-07-12 12 57 15" src="https://user-images.githubusercontent.com/39021158/42611873-4f074e54-85d3-11e8-858f-166ada7ec24f.png">
<img width="981" alt="2018-07-12 12 57 26" src="https://user-images.githubusercontent.com/39021158/42611986-b2dfc0e6-85d3-11e8-9e43-9515d7f40073.png">

I just installed react-native-get-music-files, and I get this error. what's wrong?

**Comment by lylest** [comment]
how did you solved this issues i am facing the same problem here


npm WARN react-native-get-music-files@2.1.0 requires a peer of react-native@^0.41.2 but none is installed. You must install peer dependencies yourself.
