### ISSUE TITLE
'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by jlorencelim** [cinder92/react-native-get-music-files#33]
`'React/RCTDefines.h' file not found`

It shows this error after linking. I ejected using Expokit for this.

Expo: 27.0.1
Xcode: 9.4.1
React: 16.3.1
React Native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55

**Comment by asalma02** [comment]
Having the same issue. But when I delete 'React' from the path it works: "RCTDefines.h". Kept doing this to all react errors but didn't work for yoga/Yoga.h

**Comment by cinder92** [comment]
This package does't works with expo, sorry
