### ISSUE TITLE
MusicFiles.getAll does not return anything

### ISSUE THREAD

**Issue by clems36** [cinder92/react-native-get-music-files#36]
Hi, I simply can't get anything out of `MusicFiles.getAll`...
I tried putting some logs in the module:

```js
if(Platform.OS === "android"){
    console.log('android');
    RNReactNativeGetMusicFiles.getAll(options,(tracks) => {
        console.log('tracks', tracks);
        resolve(tracks);
    },(error) => {
        console.log('error', error);
        resolve(error);
    });
}
```

this will log 'android' but not 'tracks' or 'error'. I call it this way:

```js
componentDidMount() {
    const test = MusicFiles.getAll({
        id: true,
        blured: false,
        artist: true,
        duration: true, //default : true
        cover: true, //default : true,
        title: true,
        // date: false,
        // lyrics: false,
        batchNumber: 5, //get 1 songs per batch
        minimumSongDuration: 10000, //in miliseconds,
        fields: ['title', 'artist', 'duration']
    });
    console.log('test', test);
}
```
and it logs this:
![conemu64_2018-12-03_20-37-48](https://user-images.githubusercontent.com/6041593/49397271-5a01d200-f73b-11e8-9ccb-c54eabe41f75.png)

Any help is welcome!

**Comment by clems36** [comment]
@cinder92 any ideas ?

**Comment by vszabi93** [comment]
getAll is returning promise. You have to put after the closing tag ).then to access the data so its should like this: MusicFiles.getAll({
        id: true,
        blured: false,
        artist: true,
        duration: true, //default : true
        cover: true, //default : true,
        title: true,
        // date: false,
        // lyrics: false,
        batchNumber: 5, //get 1 songs per batch
        minimumSongDuration: 10000, //in miliseconds,
        fields: ['title', 'artist', 'duration']
    }).then(tracks => {
    // do your stuff...
for example: console.log(tracks)
});

**Comment by cinder92** [comment]
i will close this issue because answered
