### ISSUE TITLE
Does this package work for iOS, for real?

### ISSUE THREAD

**Issue by harzkr** [cinder92/react-native-get-music-files#38]
I was trying to use this package to get all the music files on my device, so following the demo code in the Readme, I used the `MusicFiles.getAll()` function in componentDidMount, which is working well for Android, but doesn't show me any results for iOS. When I am listing out the `tracks` like this 

`.then(tracks => {
    console.log(tracks)
})`

, its giving me an Error, `Error, you don't have any tracks`, while I definitely do have many tracks on my device. Its showing all the tracks on Android, but doesn't work on iOS.

I have my permissions and all set up with `NSAppleMusicUsageDescription`, but still it doesn't do anything.
Was anybody able to get this working, would really be helpful, if you could guide

I'm on `iOS 12.1`, `react-native 0.57.0` and `2.1.0` of this package

**Comment by cinder92** [comment]
hello @harzkr sorry for delay answer, i will check what is going on, i think it will work only when you have songs on iTunes.

**Comment by harzkr** [comment]
I think I did on my device, but none of them were showing up. I was able to use react-native-itunes in order to display the songs, but yet, I was unable to fetch the data url of the file, which was my requirement. I am making the users copy all the songs on the folder of my app, on the Files App, and then accessing the data Url, do you think there is an easier way to fetch those, or even by using this library?
