### ISSUE TITLE
getting error as "cannot read property 'getAll' of undefined"

### ISSUE THREAD

**Issue by ranjith29h** [cinder92/react-native-get-music-files#4]
Hi when i run the code as mentioned in your read.md it shows me error like "cannot read property 'getAll' of undefined"

**Comment by cinder92** [comment]
Hello, did you try to restart your all environment?

**Comment by ranjith29h** [comment]
ya i tried it

**Comment by cinder92** [comment]
@ranjith29h  sorry for delay message, please try with this in command line `react-native link`

**Comment by tymanchik1991** [comment]
@cinder92 hi I have same issue. could you show what I need import in my MainApplication.java

because in my project when i do react-native-link its return error when try setup MainApplication

**Comment by Spartan-Arun** [comment]
@cinder92 I have the same issue as ranjith . I tried react-native link command but no luck  your package its not working at all. could you share us a working sample if possible. Thanks in advance

**Comment by cinder92** [comment]
Fixed in V2
