### ISSUE TITLE
GetAll returns all the music even though batchNumber specified

### ISSUE THREAD

**Issue by renganatha10** [cinder92/react-native-get-music-files#41]
I am Using ReactNative - 0.58
It's happening on Android

I am trying to get music on a batch of 5 but android returns all the Music

```
public getMusicFiles = async () => {
    try {
      await MusicFiles.getAll({
        id: true,
        blured: false,
        artist: true,
        duration: true, //default : true
        cover: true, //default : true,
        title: true,
        batchNumber: 5, //get 5 songs per batch
        minimumSongDuration: 100000, //in miliseconds,
        fields: [
          'title',
          'artwork',
          'duration',
          'artist',
          'genre',
          'lyrics',
          'albumTitle',
        ],
      });
    } catch (err) {
      //eslint-disable-next-line
      console.warn(err, 'error on getting music fie');
    }
  };
```

I am Listening using `DeviceEventEmitter('onBatchReceived')` it returns all the music files

Am I Missing Something?

**Comment by cinder92** [comment]
@renganatha10 how many songs do you have on your device? maybe is a stupid question, but in this way we ca check what is happening, and what are the specs of your device? simulator? real one?

**Comment by renganatha10** [comment]
I have 600 songs in a real device. I get all 600 songs in single batch and
it takes 5 to 10 minutes.

**Comment by cinder92** [comment]
@renganatha10 could you please try to install the module again from this github repo instead of npm, and test again please?

**Comment by clems36** [comment]
I'm having the same issue, `console.log(params.batch.length);` shows 5000+. It only shows `1` when I set `batchNumber: 1`
Also, i'm trying to log the result of `getAll` but it never gets to the log:

```js
async componentDidMount(): Promise<void> {
    try {
        const tracks: any = await MusicFiles.getAll({
            id: true,
            blured: false,
            artist: true,
            duration: true,
            cover: false,
            title: true,
            batchNumber: 5,
            minimumSongDuration: 10000,
            fields: ['title', 'artist', 'duration'],
        });
        console.log('number of tracks: ', tracks.length);
    } catch (err) {
        console.log('Error while getting music files: ', err);
    }
}
```

**Comment by Drazail** [comment]
@clems36 
 Does the logcat show any errors?

**Comment by renganatha10** [comment]
@cinder92 I am installing directly from GitHub FYI I am Using Android 8.1 

Screen Shot of JS console which returns the result in Batch

<img width="1005" alt="Screenshot 2019-03-18 at 4 32 47 PM" src="https://user-images.githubusercontent.com/19145173/54526356-88c74f80-499c-11e9-9bc6-a62381740021.png">


Screen Shot of Android Logcat

<img width="1399" alt="Screenshot 2019-03-18 at 4 34 29 PM" src="https://user-images.githubusercontent.com/19145173/54526371-98469880-499c-11e9-8e87-ec3d9d4f6f54.png">

**Comment by clems36** [comment]
@Drazail Yes:
![ConEmu64_2019-03-24_18-01-33](https://user-images.githubusercontent.com/6041593/54882881-f3760080-4e5e-11e9-9ccc-4548ef9eb8bf.png)
I don't understand why i'm getting this error though, why is it trying to save images ?

**Comment by Drazail** [comment]
@clems36 ```MusicFiles.getAll()``` extracts meta data directly from the file, saves the cover image and sends the path over the bridge to the JS thread, the other option is to send the image itself which would block the bridge and can cause crashes.


this is currently the only way ( and a very slow one at that) of retrieving thumbnails i can think of as ```ALBUM_ART``` constant of ```MediaStore.Audio.AlbumColumns``` was deprecated in API level Q.

**Comment by clems36** [comment]
I'm not sure I understood everything you said but basically do you have a way to avoid this error ?

**Comment by Drazail** [comment]
@clems36

There's a snippet from the example app, its a function which asks for read/write permissions recursively :

```javascrip
requestPermission = async () => {
      try {
        const granted = await PermissionsAndroid.requestMultiple(
          [
            PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
            PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE
          ],
          {
            title: "Permission",
            message: "Storage access is requiered",
            buttonPositive: "OK"
          }
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          alert("You can use the package");
        } else {
          requestPermission();
        }
      } catch (err) {
        console.warn(err);
      }
    };
```

This should fix the permission issues.

**Comment by Drazail** [comment]
@cinder92 
`com.facebook.react.bridge.WritableArray.size()` returns 1 all the time, adding a separate counter for `JsonArray` size at `com.cinder92.musicfiles.RNReactNativeGetMusicFilesModule.getSongs` should solve this issue. 

will make a pull request as soon as the docs are finalized.

**Comment by farshed** [comment]
Experiencing the same issue. Is there a workaround for it yet?

**Comment by Drazail** [comment]
@eff-society 
workaround would be to use `RNAndroidAudioStore.getAll` :p
as I mentioned earlier, the problem seems to be the return value of `com.facebook.react.bridge.WritableArray.size()` @ `com.cinder92.musicfiles.RNReactNativeGetMusicFilesModule.getSongs`.

**Comment by cinder92** [comment]
closing this in favor of https://github.com/cinder92/react-native-get-music-files/pull/108
