### ISSUE TITLE
Get all return TypeError: Cannot read property 'getAll' of undefined

### ISSUE THREAD

**Issue by M1n007** [cinder92/react-native-get-music-files#42]
this mys script 

import {
  PermissionsAndroid
} from "react-native";
import MusicFiles from "react-native-get-music-files";

  async componentDidMount() {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
        {
          title: "Listen Music App Storage Permission",
          message:
            "Listen Music App needs access to your storage " +
            "so you can listen music.",
          buttonNeutral: "Ask Me Later",
          buttonNegative: "Cancel",
          buttonPositive: "OK"
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log("You can use the camera");
      } else {
        console.log("Camera permission denied");
      }
    } catch (err) {
      console.warn(err);
    }
  }

  _getSongs = () => {
    MusicFiles.getAll({
      blured: true, // works only when 'cover' is set to true
      artist: true,
      duration: true, //default : true
      cover: false, //default : true,
      genre: true,
      title: true,
      cover: true,
      minimumSongDuration: 10000, // get songs bigger than 10000 miliseconds duration,
      fields: ["title", "albumTitle", "genre", "lyrics", "artwork", "duration"] // for iOs Version
    })
      .then(tracks => {
        console.log(tracks);
      })
      .catch(error => {
        console.log(error);
      });
  };

can someone help me ?

**Comment by farshed** [comment]
I ejected from Expo to Expokit and I'm getting the exact same error.
![Screenshot (96)](https://user-images.githubusercontent.com/23633421/54478306-74ffda00-4832-11e9-9fc2-6cf396b59b98.png)

**Comment by cinder92** [comment]
@M1n007 did you checked that ´react-native-get-music-files´ is linked correctly into Android build graddle? BTW this packaged does not work with EXPO

**Comment by M1n007** [comment]
I only use automatic link, maybe I should try the manual link.

Pada tanggal Min, 17 Mar 2019 09.03, Dante Cervantes <
notifications@github.com> menulis:

**Comment by farshed** [comment]
I solved it by creating a new vanilla React Native Project and importing all my source code into that. It works but takes 10-15 seconds to fetch around 450 audio files. @cinder92 any tips to improve its performance?

**Comment by M1n007** [comment]
@cinder92 i try to link manually but i get error result

> Configure project :app
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-get-music-files
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :react-native-get-music-files:generateDebugBuildConfig FAILED

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Unable to delete directory F:\Projects\react-native\ListenMusic\node_modules\react-native-get-music-files\android\build\generated\source\buildConfig\debug.
> Unable to delete directory F:\Projects\react-native\ListenMusic\node_modules\react-native-get-music-files\android\build\generated\source\buildConfig\debug.

**Comment by Drazail** [comment]
@eff-society the getAll method on MusicFiles class parses all the metadata including the cover directly from the music files, did you try Pagination via batchNumber option? ie:

```JavaScript
MusicFiles.getAll({
            id : true,
            blured : false,
            artist : true,
            duration : true, 
            cover : true,,
            title : true,
            cover : true,
            batchNumber : 5, // this option
            minimumSongDuration : 10000
            fields : ['title','artwork','duration','artist','genre','lyrics','albumTitle']
        });

```

Also on android >=5 you can use RNAndroidAudioStore.getSongs with no arguments ( ie:

```JavaScript
RNAndroidAudioStore.getSongs().then(res=>console.log(res)).catch(er=>console.log(er))
```
)
to retrieve all the songs from androids internal metadata database, this method will be faster however if some songs haven't been scanned by android or if their meta data is not supported by android scanner they wont show up correctly.

(the documentation on the RNAndroidAudioStore is missing from the readme though, ill add it asap, meanwhile you can find the example app [here](https://github.com/cinder92/react-native-get-music-files/tree/master/example). )

@M1n007 can you please reproduce the issue by making a public repo so we can go through the code?

Also have you tried sync/clean build?

**Comment by M1n007** [comment]
this my public repo, can you help me about new error 
https://github.com/M1n007/ListenMusic

**Comment by Drazail** [comment]
@M1n007: seems to be working as intended : 

![RNGMFIssue#42](https://user-images.githubusercontent.com/30296570/55039968-0bf34000-5044-11e9-949f-77b7f28bdc49.jpg)

the only error this throws is due to lack of write permission which is required in order to save the album-art.

**Comment by M1n007** [comment]
@Drazail @cinder92 
yes for now after I try this again it works, thanks in advance.
