### ISSUE TITLE
Last updates doesn't makes effect on existing installation 

### ISSUE THREAD

**Issue by ithustle** [cinder92/react-native-get-music-files#44]
Updating on new installation doesn't change last commit done on this package. I think should be a better approach release 2.1.1 version.

**Comment by Drazail** [comment]
@ithustle are you updating via npm or GitHub?

**Comment by ithustle** [comment]
`npm`. To be more specific, `yarn`

**Comment by Drazail** [comment]
I think it hasn't been updated on npm yet, I may be wrong though.

**Comment by cinder92** [comment]
@ithustle please use git repo instead npm

**Comment by ithustle** [comment]
@cinder92, roger that. Thanks.
