### ISSUE TITLE
RNAndroidAudioStore TypeError: Cannot read property 'getSongs' of undefined

### ISSUE THREAD

**Issue by farshed** [cinder92/react-native-get-music-files#45]
Hello, I'm trying to use RNAndroidAudioStore as mentioned by @Drazail in https://github.com/cinder92/react-native-get-music-files/issues/42#issuecomment-473815037 but it seems to be undefined.

I'm importing it like so:
`import MusicFiles, { RNAndroidAudioStore } from 'react-native-get-music-files';`

Is this is a recent addition to react-native-get-music-files? Do I need to update the lib to make it work or what?

**Comment by Drazail** [comment]
@eff-society yes, this is a new addition, you will need to install the package via GitHub and follow the instructions given [here](https://github.com/Drazail/react-native-get-music-files/blob/development/README.md) specifically these steps: 

> A new Class called RNAndroidAudioStore is implemented and should be imported separately in MainApplication.java ( if the functionality is need of course):
```Java
import com.drazail.rnandroidstore.RNAndroidStorePackage;
```

```Java
new RNAndroidStorePackage()
```
you can also find the example app [here](https://github.com/cinder92/react-native-get-music-files/tree/master/example)

please note that the default export of the module has not been changed, so this update should be 100% backwards compatible.

 I am sorry for the inconvenience, will make a pull request with updated docs as soon as possible.

ps. pagination isn't implemented on RNAndroidAudioStore's methods yet and will be added in the next pull request.

**Comment by farshed** [comment]
I followed your instructions but now the android studio throws me the following errors:
```
 error: package com.reactlibrary does not exist
import com.reactlibrary.RNReatNativeGetMusicFilesPackage;
error: package com.drazail.rnandroidstore does not exist
import com.drazail.rnandroidstore.RNAndroidStorePackage;
error: cannot find symbol
            new RNAndroidStorePackage()
```

I installed the package via github with `yarn add Drazail/react-native-get-music-files`

**Comment by farshed** [comment]
@Drazail A little help please!

**Comment by Drazail** [comment]
@eff-society, can you reproduce the issue in a public repo?

ps. if you want to install from my fork ( which i don't advise as it hasn't been tested), then you should use the development branch, not the master, ie : you should include the following in the package.json : 
```javascript
"dependencies": {
    ...,
    "react-native-get-music-files": "git+https://github.com/Drazail/react-native-get-music-files.git#development",
    ...
  },
```

anyways, please reproduce the issue so i can take deeper dive into it.

**Comment by farshed** [comment]
It seems I wasn't installing the lib correctly. Did what you said and got it working (only to find out that RNAndroidAudioStore doesn't return artwork paths 😁, which is necessary for my project). Guess I'll have to stick with the MusicFiles. Anyway, thanks for all the help.

**Comment by Drazail** [comment]
@eff-society 

unfortunately the `ALBUM_ART` constant of `MediaStore.Audio.AlbumColumns` was deprecated in API level `Q` and always returns `null`, so there is no way of accessing the covers android extracts on each scan. the only way to get the covers currently is to extract the metadata directly from the file itself, save it and send the path over to JS, which as you can imagine is very slow. here i can think of two solutions:

1-  you can use other methods of `RNAndroidAudioStore`, for instance, you can query the songs using `search` or `getSongs`, and then get the covers of the songs you want to show to the user via `getSongByPath({songUri: 'path to the song', cover: true})`.

2-  if you are using the development branch of my fork ( i made a pull request yesterday, so it should be merged into masters branch of this repo soon) you can use `RNAndroidAudioStore.getAll` with `batchNumber` and `delay` options specified to implement some sort of pagination.

having said that, I do understand the importance of proper pagination. we have internally implemented  pagination for `RNAndroidAudioStore.search`, however it hasn't been tested yet, will add it to this module as soon as that's done.

**Comment by Joshmatjjen** [comment]
I am still getting TypeError: Cannot read property 'getSong' of undefined

**Comment by Joshmatjjen** [comment]
> It seems I wasn't installing the lib correctly. Did what you said and got it working (only to find out that RNAndroidAudioStore doesn't return artwork paths , which is necessary for my project). Guess I'll have to stick with the MusicFiles. Anyway, thanks for all the help.

How did you install it this time

**Comment by farshed** [comment]
@Joshmatjjen Follow the instructions in the manual linking section. Then, uninstall the app from your device/emulator and rebuild. That should work.

**Comment by Joshmatjjen** [comment]
@farshed  I have done that..  i am getting an error that says: 

null is not an object (evaluating 'RNAndroidStore.getSongByPath')

**Comment by Joshmatjjen** [comment]
@farshed Only getAll function works well

**Comment by farshed** [comment]
@Joshmatjjen sorry I have no idea what the problem might be.

**Comment by Drazail** [comment]
@Joshmatjjen 
> null is not an object (evaluating 'RNAndroidStore.getSongByPath')

Are you sure your imports are correct? ( Try 'RNAndroidAudioStore' instaed of 'RNAndroidStore')

 If every thing is done properly, please reproduce the issue and share the code with us.

**Comment by Joshmatjjen** [comment]
@Drazail  I have created a new Issue

**Comment by Joshmatjjen** [comment]
Here is the link:
 https://github.com/cinder92/react-native-get-music-files/issues/74
