### ISSUE TITLE
 error: cannot find symbol new RNReactNativeGetMusicFilesPackage(),

### ISSUE THREAD

**Issue by yusuf987** [cinder92/react-native-get-music-files#47]
My project info 
    "react-native": "0.49.3",
    "react-native-get-music-files": "^2.1.0",
platform : Android

after follow all step i am not able to build the project in android saying bellow error 

` error: cannot find symbol new RNReactNativeGetMusicFilesPackage(),`

can somebody please help me

**Comment by Drazail** [comment]
@yusuf987
Have you linked the project manually?
If so, try replacing `import com.reactlibrary.RNReatNativeGetMusicFilesPackage;` with `mport com.cinder92.musicfiles.RNReatNativeGetMusicFilesPackage` in `android/app/src/main/java/[...]/MainActivity.java`

**Comment by yusuf987** [comment]
i have done both manual and automatic,
but i am confused as per documentation  
![image](https://user-images.githubusercontent.com/24749530/56261724-bfa69780-60f9-11e9-9e9c-bbc9068ded48.png)
`it saying Add new RNReatNativeGetMusicFilesPackage() to the list returned by the getPackages() method` ,
but there is no **getPackages()** in **MainActivity.java** instead it is in **MainApplication.java** so i  add the code in **MainApplication.java**

`import com.cinder92.musicfiles.RNReatNativeGetMusicFilesPackage` is autometacly added in my **MainApplication.java** when i run `react-native link react-native-get-music-files`

can you please clear my confusion

**Comment by Drazail** [comment]
@yusuf987 yes, seems like `MainActivity.java` is a type and should be `android/app/src/main/java/[...]/MainApplication.java`

please check the [example ](https://github.com/cinder92/react-native-get-music-files/tree/master/example)app and see if that helps, if not, then please reproduce the issue in a public repo so we can take a closer look.

**Comment by yusuf987** [comment]
yes the issue was due to the wrong name mentioned in docs 
now I am able to build succeed after following only 2 steps bellow
(1 ) run react-native link react-native-get-music-files
(2)  adding      `compile project(':react-native-get-music-files')`
in app/build gradle 

thanks for help

**Comment by diegoareval** [comment]
@yusuf987 could show me the build.gradle code and myapplication code, because i got the same error
