### ISSUE TITLE
can only read music file from Audio folder

### ISSUE THREAD

**Issue by yusuf987** [cinder92/react-native-get-music-files#48]
My project info
"react-native": "0.49.3",
"react-native-get-music-files": "^2.1.0",
platform : Android

i wand to read all call recording file from the device and i am also getting some files(.amr) from Audio folder of android
but  not all the files 

like i have installed two call recording apps in my android phones say (App1 and App2) 
and records come calls from both the apps
app1 recorded files are showing in Audio folder and i am able to read those file and other audio players as well
but App2 files are  present only in their own created folders so nor i or any other audio player showing the files

does this library scan only Audio folder ???

**Comment by Drazail** [comment]
@yusuf987 

no, this library does indeed scan the whole device.

however, to find music files, this package queries Android's MediaStore.Audio with the flag IsMusic set to true, so there are two requirements for this package to find the files:  

1- Android should have already scanned the file
2- the file should be a music file

does App2 use its own proprietary MIME type? if not, does it make a request to the android scanner? if not, have you tried to restart the device to see if the records become available or not?

if you do know the path to the file, you can use [RNAndroidStore.getSongByPath](https://github.com/Drazail/react-native-get-music-files/tree/development) to retrieve the metadata or alternatively you can use a library like [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob) if you just need a simple ls.

**Comment by yusuf987** [comment]
I have tried to restart the device with  no luck 
the files in app2 has  **.amr** extension 

can you help me how do i check if the App2 make a request to the android scanner 

thank you

**Comment by Drazail** [comment]
@yusuf987  does android's own music player show these records?

**Comment by lylest** [comment]
can we build this library using react-native fs to open and find all files related to audio files and store their path to the state or something then we can retrieve them in flat list or something  i am currently working on that my app could run with rn-fetch-blob so this is my only solution still trying though

**Comment by Drazail** [comment]
@lylest

That will most probably crash your app.

What are the unimplemented features that you are looking for?

**Comment by lylest** [comment]
No have tried open all directories and read all music paths and store the  in state and it worked just fine

**Comment by Drazail** [comment]
@lylest

I assume you'll then want to extract the meta data, scale this up to a couple of thousands of songs and your app will crash.

I still don't understand what fs has to do with what we try to solve with this package.

**Comment by lylest** [comment]
I'll try it anyway and make it more even better
