### ISSUE TITLE
Cover folder

### ISSUE THREAD

**Issue by ghost** [cinder92/react-native-get-music-files#49]
Cover images extracted directly to internal storage. I need to change output folder. I don't know can we set because of poor readme... (I can't set it directly in java, i need to set programmatically)

**Comment by Drazail** [comment]
@TrueTiem 

It is possible to change the folder in which the images are stored via `RNAndroidAudioStore` , ie:

```Javascript
RNAndroidAudioStore.getAll({
...
coverFolder: 'path to folder',
...
});
```
or
```Javascript
RNAndroidAudioStore.getSongByPath({
...
coverFolder: 'path to folder',
...
});
```

As for documentation, I made a pull request ( updated docs & batchNumber/delay on `RNAndroidAudioStore.getAll`) and its waiting for approval, meanwhile please check the development branch of my [fork](https://github.com/Drazail/react-native-get-music-files/tree/development) for full documentation on `RNAndroidAudioStore`.

please note that you need to install via GitHub to have access to `RNAndroidAudioStore` as the npm version has not been updated yet.

**Comment by TrueTiem** [comment]
Hi, thanks for reply. I installed from development branch but get `TypeError: RNAndroidStore is undefined`

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: RNAndroidStore is undefined
getAll/<@blob:http://localhost:8081/4db2acac-62c6-4189-b69f-9c03231e012a:99292:11
```

**Comment by ghost** [comment]
It was only allowing me to save inside the folder returned from getExternalStorageDirectory(). I just simply changed that. Working perfectly <3
