### ISSUE TITLE
Support for react native 0.60

### ISSUE THREAD

**Issue by YajanaRao** [cinder92/react-native-get-music-files#54]
Is there a support for AndroidX or react native version 0.60 ?

**Comment by Drazail** [comment]
@YajanaRao

Not yet. I'm currently working on it though.

**Comment by YajanaRao** [comment]
Thank you @Drazail 

I am facing issue with `npx jetify`. I am getting error as 
`[TypeError: null is not an object (evaluating 'RNAndroidStore.getArtists')]`.
Any timeline for the react native version 0.60 support

**Comment by Drazail** [comment]
@YajanaRao 
`RNAndroidStore` needs some refactoring to be compatible with jetify.
Unfortunately I am struggling with some health issues at the moment hence the slow development process at my end, however the new version will hopefully be pushed by the end of this month.

**Comment by Drazail** [comment]
@YajanaRao 

I was playing around with `jetifier` today, and to my surprise the latest version worked.

is it the `npx jetify` that's throwing you this error?

**Comment by YajanaRao** [comment]
Using jetify I can access musicfiles but not RNAndroidStore.

**Comment by Drazail** [comment]
@YajanaRao 
`import { RNAndroidAudioStore } from "react-native-get-music-files";`

**Comment by Drazail** [comment]
@YajanaRao

Please update the status on this issue.

**Comment by YajanaRao** [comment]
I will close this issue as the solution is using jetify
