### ISSUE TITLE
onLastBatchReceived event isn't triggered

### ISSUE THREAD

**Issue by farshed** [cinder92/react-native-get-music-files#56]
I'm using RNAndroidAudioStore's `getAll` method with pagination. The `onBatchReceived` event is triggered correctly but the `onLastBatchReceived` callback is never executed. I haven't tested this with MusicFiles yet.

I'm using the master version with react-native 0.59.9 and testing on Android Pie.

**Comment by Drazail** [comment]
@eff-society 
Its probably an edge case, ill take a look asap.
meanwhile please test with different batch sizes and see if it helps.

**Comment by myckhel** [comment]
Im using the master repo as well

Same issue here testing with 2 different devices.

Also RNAndroidStore throws error while trying to use any of its method.
Error e.g cannot get property getAll of undefined.

Also if batchNumber is greater than 1
MusicFiles returns all files at once exept if specify 1 batchNumber before it returns 1 file at a time.

Would really appreciate if these errors would be look into.

Thank you.

**Comment by farshed** [comment]
> Also RNAndroidStore throws error while trying to use any of its method.
> Error e.g cannot get property getAll of undefined.

This might be because RNAndroidStore is not properly linked. Make sure to follow the manual linking instructions [here](https://github.com/cinder92/react-native-get-music-files#manual-installation-1).


> Also if batchNumber is greater than 1
> MusicFiles returns all files at once exept if specify 1 batchNumber before it returns 1 file at a time.

The [workaround](https://github.com/cinder92/react-native-get-music-files/issues/41#issuecomment-503911492) for this is to use RNAndroidStore instead.

**Comment by jile10** [comment]
still an issue. 0.61

**Comment by cinder92** [comment]
closing this in favor of https://github.com/cinder92/react-native-get-music-files/pull/108
