### ISSUE TITLE
The `RNReactNativeGetMusicFiles` pod failed to validate due to 1 error:

### ISSUE THREAD

**Issue by therealsuji** [cinder92/react-native-get-music-files#69]
[!] The `RNReactNativeGetMusicFiles` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.

to anyone that couldn't fix this to fix this go to the react-native-get-music-files in node modules and replace home in podspec with this

  s.homepage     = "https://github.com/cinder92/react-native-get-music-files"

**Comment by fanyui** [comment]
Great @therealsuji  I had exact same issue and your proposal worked 👍 .

**Comment by badris101** [comment]
Great job @therealsuji  👍

**Comment by Hamashassan** [comment]
I am facing this error while running pod install but as mentioned above There is no podspec file inside the path **node_modules/react-native-get-music-files/**, please let me know what to do. Thanks!

**Comment by Sajfan** [comment]
Good job @therealsuji 👍  This worked for me...

**Comment by baby3301** [comment]
> I am facing this error while running pod install but as mentioned above There is no podspec file inside the path **node_modules/react-native-get-music-files/**, please let me know what to do. Thanks!

node_modules/react-native-get-music-files/ios/
