### ISSUE TITLE
How can i make MusicFiles.get() Asynchronous?

### ISSUE THREAD

**Issue by themakerman** [cinder92/react-native-get-music-files#7]
The library is awesome but it has been really a pain when you execute MusicFiles.get() function as the UI thread hangs up due to processing. To overcome this i did tried using progressbar but its not working out. How can i make it Async??

**Comment by cinder92** [comment]
this is a nice question, i think i can make it run it in another `thread` in order to prevent UI blocking

**Comment by themakerman** [comment]
@cinder92 Can you just tell me when will you be updating the code cause i am using this library on production app for music data retrieval which is the most important part and i am stuck now.

**Comment by cinder92** [comment]
@themakerman PR are welcome :)

**Comment by flarocca** [comment]
@themakerman I will be working on that soon.
I'm evaluating two different alternatives always working asynchronously in order to prevent the UI thread from blocking:

1. Return batches so that your callback will be called each 10 files (this could be for units, batch size or time) read.
2. Keep the same behavior as now and return all at once.

I think batching would be nicer and more effective, but I'd like to know @cinder92 's thoughts

**Comment by cinder92** [comment]
@flarocca great job! I will be working on this package today in order to make this fixes and implement iOS version, keep in touch

**Comment by flarocca** [comment]
Let me know if you need help.
I'll be working on doing this but asynchronously in order to avoid blocking the UI. Perhaps I could do some batching too.

**Comment by cinder92** [comment]
Fixed in V2

**Comment by themakerman** [comment]
@cinder92 @flarocca so have you implemented a callback for batching? Ideally this would be great to have so that we can update some component (eg: progressBar) to show users the progress of file scan.

**Comment by flarocca** [comment]
No yet, but would be the target.

**Comment by cinder92** [comment]
We moved the songs retrieving to another thread that prevents ui blocking , you can put an activity indicator while songs retrieving ends

**Comment by themakerman** [comment]
@cinder92 yup thats what i am doing right now. @flarocca it would be good if we keep batching as the target as that would be considered real time status and great engineering :)

**Comment by flarocca** [comment]
That would be nice!!!

**Comment by cinder92** [comment]
@themakerman please use last commit with, `batchNumber` option, for more info, please check docs :)

**Comment by themakerman** [comment]
@cinder92 since it works on iOS as well now update the title of the library in readme. Currently says

react-native-get-music-files:
React Native package to get music files from local and sd for Android (only)

Great work. I am really excited to bump v2 to my production app. Will share the results with you. Thanks.
