### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNReactNativeGetMusicFiles.getAll')

### ISSUE THREAD

**Issue by therealsuji** [cinder92/react-native-get-music-files#70]
2019-11-25 22:14:45.030 [info][tid:com.facebook.react.JavaScript] { [TypeError: null is not an object (evaluating 'RNReactNativeGetMusicFiles.getAll')]
  line: 96542,
  column: 37,
  sourceURL: 'http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&minify=false' }

this comes up when i try to get all songs in ios 13.1

pod install was done also automatic linking is done as well

**Comment by Drazail** [comment]
@therealsuji 

can you provide more context?

**Comment by SpQuyt** [comment]
Android is normal. But not with iOS

**My environment**
* react-native: 0.62.1
* react: 16.11.0
* react-native-get-music-files: 2.1.0
* Xcode: 10.3

**My error**
![image](https://user-images.githubusercontent.com/17812909/81720087-1ec70f00-94a8-11ea-9fe0-2dcfb429cdb4.png)

**Comment by Drazail** [comment]
I don't know about iOS part of the module, maybe @cinder92  can help.

**Comment by PreetOceans** [comment]
TypeError: null is not an object (evaluating 'RNReactNativeGetMusicFiles.getAll') getting this error on android. 
add library folder in project because from npm install getting error

**Comment by anhphung97** [comment]
Anyone knows how to fix this? Having this problem in iOS as well. cc: @cinder92

**Comment by amau808** [comment]
Is there a solution ? I'm facing the same issue on ios (using the simulator).

I didn't follow the installation instructions because, if I modify the Xcode project, it doesn't compile anymore

**Comment by MaxJadav** [comment]
Fetch same error iOS Any update on this? Is there a solution ?
_TypeError: null is not an object (evaluating 'RNReactNativeGetMusicFiles.getAll')_

**Comment by cinder92** [comment]
closing this in favor of https://github.com/cinder92/react-native-get-music-files/pull/108
