### ISSUE TITLE
ackage android.support.annotation does not exist

### ISSUE THREAD

**Issue by kaneki666** [cinder92/react-native-get-music-files#79]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
65 actionable tasks: 12 executed, 53 up-to-date
E:\Programming\javascript\react-native\Kaze\node_modules\react-native-get-music-files\android\src\main\java\com\cinder92\musicfiles\RNReactNativeGetMusicFilesModule.java:20: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
E:\Programming\javascript\react-native\Kaze\node_modules\react-native-get-music-files\android\src\main\java\com\cinder92\musicfiles\RNReactNativeGetMusicFilesModule.java:342: error: cannot find symbol
                           @Nullable WritableMap params) {
                            ^
  symbol:   class Nullable
  location: class RNReactNativeGetMusicFilesModule
2 errors

i have no idea whats the error ? can anyone help me??

**Comment by kaneki666** [comment]
i turned off jetifier so i see this error

**Comment by pluvd7j** [comment]
$ npm i jetifier
$ npx jetify
install these two commands and add the below line in your gradle.properties
android.useAndroidX=true
android.enableJetifier=true 

and set the minSdkversion as 17 in android--->build.gradle (Minimum version 17  you can also use higher)
