### ISSUE TITLE
Something get wrong with musicCursor

### ISSUE THREAD

**Issue by kaneki666** [cinder92/react-native-get-music-files#80]
RNAndroidAudioStore.getAll({
         title: true,
	artist: true,
	album: true,
	duration: true,
	cover: true,
	blured: false,
      
});

i am using physical device and i have music files in it! any help would be appreciated! Thank you

**Comment by Drazail** [comment]
@kaneki666 
files are not added to the android DataBase, so you either recently added them, or they are located in a nomedia folder

**Comment by cinder92** [comment]
closing this in favor of https://github.com/cinder92/react-native-get-music-files/pull/108
