### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNReactNativeGetMusicFiles.getAll')

### ISSUE THREAD

**Issue by Arwik228** [cinder92/react-native-get-music-files#81]
![image](https://user-images.githubusercontent.com/42431675/90425152-bc019700-e0d8-11ea-83d7-222a688f4c36.png)
![image](https://user-images.githubusercontent.com/42431675/90425194-ce7bd080-e0d8-11ea-9d3a-1dd91efb6617.png)
![image](https://user-images.githubusercontent.com/42431675/90425324-fff49c00-e0d8-11ea-9f5c-05f22cca28c1.png)

**Comment by cinder92** [comment]
closing this in favor of https://github.com/cinder92/react-native-get-music-files/pull/108
