### ISSUE TITLE
assetUrl key not in track response  

### ISSUE THREAD

**Issue by JrajsinhZala** [cinder92/react-native-get-music-files#86]
i am a using this library for get music list and it's working file but i am not getting asseUrl(path) in ios
i pass this option
{
        id: true,
        blured: true,
        artist: true,
        duration: true,
        cover: true,
        genre: true,
        title: true,
        fields : ['title','albumTitle','genre','lyrics','artwork','duration'] // for iOs Versio
      }

**Comment by NautamSanghani** [comment]
hey @JrajsinhZala have you found any solutions ??

**Comment by JrajsinhZala** [comment]
No i can't

**Comment by cinder92** [comment]
closing this in favor of https://github.com/cinder92/react-native-get-music-files/pull/108
