### ISSUE TITLE
Attempt to invoke virtual method [Error]

### ISSUE THREAD

**Issue by mrzjordan** [cinder92/react-native-get-music-files#9]
Trying to fetch all music in my local storage(Internal and SD card} in ComponentDidMount but my app is giving this error.
![Error](https://user-images.githubusercontent.com/19315604/30300401-e98a910c-976d-11e7-910a-123a65399cb0.png)

![My code here](https://user-images.githubusercontent.com/19315604/30300444-17dc68fa-976e-11e7-9dc4-2c9b947a44da.png)

react-native :0.48.2
wix-react-native-navigation:1.12.2

**Comment by themakerman** [comment]
@mnehal69 please check if react-native run-android is working when you add the library in your project.

**Comment by cinder92** [comment]
Fixed in V2
