### ISSUE TITLE
 error [Error: 404: Either the cursor is null or there are no results for this query]

### ISSUE THREAD

**Issue by ajoykarmakar** [cinder92/react-native-get-music-files#91]
error [Error: 404: Either the cursor is null or there are no results for this query]. Got this error on android 10+ only.

![image](https://user-images.githubusercontent.com/32778214/100723657-0be63e80-33e8-11eb-9cc7-7a50f146ac30.png)

Packages - 
    "react": "16.13.1",
    "react-native": "0.63.2",

**Comment by cinder92** [comment]
@ajoykarmakar Did you request permissions to read files?

**Comment by cinder92** [comment]
closing this due to not response
